pipeline {
  agent any

  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockehub-creds')
    AWS_REGION = "us-east-1"
  }

  stages {
    stage('Clone Repository') {
      steps {
        git branch : 'main', url: 
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
docker.build("jagadeesh7893/nodejs-app:${BUILD_NUMBER}")
        }
      }
    }

    stage('Pudh to Docker Hub') {
      steps {
        script {
docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
  docker.image("jagadeesh7893/nodejs-app:23:${BUILD_NUMBER}").push()
          }
        }
      }
    }
    stage('Provision AWS EC2 (Terrafrom)'){
      dir('terraform') {
        steps {
          sh 'terraform init'
          sh 'terraform apply-auto-approve'
        }
      }
    }
    stage('Deploy app (Ansible)') {
      dir('ansible') {
        steps {
          sh 'ansible-playbook -i hosts playbook.yml'
        }
      }
    }
  }
    
